### ISSUE TITLE
[Question❓] Tests for GPU implementation skipped, because of missing packages

### ISSUE THREAD

**Issue by ghazni123** [pymatting/pymatting#30]
Hi

I have setup the pymatting under container environment and executed the test. Pytest was able to complete it however I got following warnings:

tests/test_foreground.py::test_foreground
  /pymatting/tests/test_foreground.py:32: UserWarning: Tests for GPU implementation skipped, because of missing packages.
    "Tests for GPU implementation skipped, because of missing packages."

-- Docs: https://docs.pytest.org/en/stable/warnings.html

I noticed that similar issue was reported earlier as well but couldn't find conclusion 

I have got Nvidia GPUs but somehow it is not being detected. I have individually installed cuPy, pyopencl, libcutensor and some other output on installed cuda packages:

```
root@10e16f343455:/pymatting# dpkg --list | grep cuda
ii  cuda-command-line-tools-10-2  10.2.89-1                           amd64        CUDA command-line tools
ii  cuda-compat-10-2              440.95.01-1                         amd64        CUDA Compatibility Platform
ii  cuda-compiler-10-2            10.2.89-1                           amd64        CUDA compiler
ii  cuda-cudart-10-2              10.2.89-1                           amd64        CUDA Runtime native Libraries
ii  cuda-cudart-dev-10-2          10.2.89-1                           amd64        CUDA Runtime native dev links, headers
ii  cuda-cufft-10-2               10.2.89-1                           amd64        CUFFT native runtime libraries
ii  cuda-cufft-dev-10-2           10.2.89-1                           amd64        CUFFT native dev links, headers
ii  cuda-cuobjdump-10-2           10.2.89-1                           amd64        CUDA cuobjdump
ii  cuda-cupti-10-2               10.2.89-1                           amd64        CUDA profiling tools runtime libs.
ii  cuda-cupti-dev-10-2           10.2.89-1                           amd64        CUDA profiling tools interface.
ii  cuda-curand-10-2              10.2.89-1                           amd64        CURAND native runtime libraries
ii  cuda-curand-dev-10-2          10.2.89-1                           amd64        CURAND native dev links, headers
ii  cuda-cusolver-10-2            10.2.89-1                           amd64        CUDA solver native runtime libraries
ii  cuda-cusolver-dev-10-2        10.2.89-1                           amd64        CUDA solver native dev links, headers
ii  cuda-cusparse-10-2            10.2.89-1                           amd64        CUSPARSE native runtime libraries
ii  cuda-cusparse-dev-10-2        10.2.89-1                           amd64        CUSPARSE native dev links, headers
ii  cuda-driver-dev-10-2          10.2.89-1                           amd64        CUDA Driver native dev stub library
ii  cuda-gdb-10-2                 10.2.89-1                           amd64        CUDA-GDB
ii  cuda-libraries-10-2           10.2.89-1                           amd64        CUDA Libraries 10.2 meta-package
ii  cuda-libraries-dev-10-2       10.2.89-1                           amd64        CUDA Libraries 10.2 development meta-package
ii  cuda-license-10-2             10.2.89-1                           amd64        CUDA licenses
ii  cuda-memcheck-10-2            10.2.89-1                           amd64        CUDA-MEMCHECK
ii  cuda-minimal-build-10-2       10.2.89-1                           amd64        Minimal CUDA 10.2 toolkit build packages.
ii  cuda-misc-headers-10-2        10.2.89-1                           amd64        CUDA miscellaneous headers
ii  cuda-npp-10-2                 10.2.89-1                           amd64        NPP native runtime libraries
ii  cuda-npp-dev-10-2             10.2.89-1                           amd64        NPP native dev links, headers
ii  cuda-nvcc-10-2                10.2.89-1                           amd64        CUDA nvcc
ii  cuda-nvdisasm-10-2            10.2.89-1                           amd64        CUDA disassembler
ii  cuda-nvgraph-10-2             10.2.89-1                           amd64        NVGRAPH native runtime libraries
ii  cuda-nvgraph-dev-10-2         10.2.89-1                           amd64        NVGRAPH native dev links, headers
ii  cuda-nvjpeg-10-2              10.2.89-1                           amd64        NVJPEG native runtime libraries
ii  cuda-nvjpeg-dev-10-2          10.2.89-1                           amd64        NVJPEG native dev links, headers
ii  cuda-nvml-dev-10-2            10.2.89-1                           amd64        NVML native dev links, headers
ii  cuda-nvprof-10-2              10.2.89-1                           amd64        CUDA Profiler tools
ii  cuda-nvprune-10-2             10.2.89-1                           amd64        CUDA nvprune
ii  cuda-nvrtc-10-2               10.2.89-1                           amd64        NVRTC native runtime libraries
ii  cuda-nvrtc-dev-10-2           10.2.89-1                           amd64        NVRTC native dev links, headers
ii  cuda-nvtx-10-2                10.2.89-1                           amd64        NVIDIA Tools Extension
ii  cuda-sanitizer-api-10-2       10.2.89-1                           amd64        CUDA Sanitizer API
hi  libcudnn7                     7.6.5.32-1+cuda10.2                 amd64        cuDNN runtime libraries
ii  libcudnn7-dev                 7.6.5.32-1+cuda10.2                 amd64        cuDNN development libraries and headers
hi  libnccl-dev                   2.7.8-1+cuda10.2                    amd64        NVIDIA Collectives Communication Library (NCCL) Development Files
hi  libnccl2                      2.7.8-1+cuda10.2                    amd64        NVIDIA Collectives Communication Library (NCCL) Runtime
```

Could you please advise on what package might be missing? Thank you.

**Comment by tuelwer** [comment]
Hi @ghazni123, the test script only checks if pyopencl and cupy can be imported without errors. Could you try to import the packages? You can do so by running `python3 -c "import pyopencl"` and `python3 -c "import cupy"`. Both commands should not produce any output if pyopencl and cupy are installed correctly.

**Comment by ghazni123** [comment]
Many thanks for your reply. I have checked below is the output. turns out that pyopencl was installed correctly but cupy wasn't. It is looking for cuda shared library which it is not finding.

I'll investigate this. Thanks again.

Regards,


root@da28089b2e45:/pymatting# python3 -c "import pyopencl"

root@da28089b2e45:/pymatting# python3 -c "import cupy"
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cupy/__init__.py", line 20, in <module>
    from cupy import core  # NOQA
  File "/usr/local/lib/python3.6/dist-packages/cupy/core/__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/cupy/__init__.py", line 41, in <module>
    raise ImportError(_msg) from e
ImportError: CuPy is not correctly installed.

If you are using wheel distribution (cupy-cudaXX), make sure that the version of CuPy you installed matches with the version of CUDA on your host.
Also, confirm that only one CuPy package is installed:
  $ pip freeze

If you are building CuPy from source, please check your environment, uninstall CuPy and reinstall it with:
  $ pip install cupy --no-cache-dir -vvvv

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

original error: libcuda.so.1: cannot open shared object file: No such file or directory

**Comment by ghazni123** [comment]
Ok I have resolved the issue related with missing library and got the clean output from the those commands

root@8108cd8da725:/pymatting# python3 -c "import pyopencl"
root@8108cd8da725:/pymatting# python3 -c "import cupy"
root@8108cd8da725:/pymatting# 

after this i executed pytest. 10 tests passed but 1 failed with following error:

E   pyopencl._cl.LogicError: clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR

/usr/local/lib/python3.6/dist-packages/pymatting/foreground/estimate_foreground_ml_pyopencl.py:97: LogicError

FAILED tests/test_foreground.py::test_foreground - pyopencl._cl.LogicError: clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR

1 failed, 10 passed in 61.21s (0:01:01) 

root@8108cd8da725:/pymatting# 

Regards,
Ghazni

Detailed log is as below:


```
root@8108cd8da725:/pymatting# pytest
======================================================================================================================= test session starts ========================================================================================================================
platform linux -- Python 3.6.9, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: /pymatting
collected 11 items                                                                                                                                                                                                                                                 

tests/test_boxfilter.py .                                                                                                                                                                                                                                    [  9%]
tests/test_cg.py .                                                                                                                                                                                                                                           [ 18%]
tests/test_estimate_alpha.py .                                                                                                                                                                                                                               [ 27%]
tests/test_foreground.py F                                                                                                                                                                                                                                   [ 36%]
tests/test_ichol.py .                                                                                                                                                                                                                                        [ 45%]
tests/test_kdtree.py .                                                                                                                                                                                                                                       [ 54%]
tests/test_laplacians.py .                                                                                                                                                                                                                                   [ 63%]
tests/test_lkm.py .                                                                                                                                                                                                                                          [ 72%]
tests/test_preconditioners.py .                                                                                                                                                                                                                              [ 81%]
tests/test_simple_api.py .                                                                                                                                                                                                                                   [ 90%]
tests/test_util.py .                                                                                                                                                                                                                                         [100%]

============================================================================================================================= FAILURES =============================================================================================================================
_________________________________________________________________________________________________________________________ test_foreground __________________________________________________________________________________________________________________________

    def test_foreground():
        try:
            from pymatting.foreground.estimate_foreground_ml_cupy import (
                estimate_foreground_ml_cupy,
            )
>           from pymatting.foreground.estimate_foreground_ml_pyopencl import (
                estimate_foreground_ml_pyopencl,
            )

tests/test_foreground.py:16: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    import numpy as np
    import pyopencl as cl
    
    source = """
    __kernel void resize_nearest(
        __global float *dst,
        __global const float *src,
        int w_src, int h_src,
        int w_dst, int h_dst,
        int depth
    ){
        int x_dst = get_global_id(0);
        int y_dst = get_global_id(1);
    
        if (x_dst >= w_dst || y_dst >= h_dst) return;
    
        int x_src = min(x_dst * w_src / w_dst, w_src - 1);
        int y_src = min(y_dst * h_src / h_dst, h_src - 1);
    
        __global       float *ptr_dst = dst + (x_dst + y_dst * w_dst) * depth;
        __global const float *ptr_src = src + (x_src + y_src * w_src) * depth;
    
        for (int channel = 0; channel < depth; channel++){
            ptr_dst[channel] = ptr_src[channel];
        }
    }
    
    __kernel void ml_iteration(
        __global       float *F,
        __global       float *B,
        __global const float *F_prev,
        __global const float *B_prev,
        __global const float *image,
        __global const float *alpha,
        int w,
        int h,
        float regularization
    ){
        int x = get_global_id(0);
        int y = get_global_id(1);
    
        int i = x + y * w;
    
        if (x >= w || y >= h) return;
    
        float a0 = alpha[i];
        float a1 = 1.0f - a0;
    
        float b00 = a0 * image[i * 3 + 0];
        float b01 = a0 * image[i * 3 + 1];
        float b02 = a0 * image[i * 3 + 2];
    
        float b10 = a1 * image[i * 3 + 0];
        float b11 = a1 * image[i * 3 + 1];
        float b12 = a1 * image[i * 3 + 2];
    
        int js[4] = {
            max(    0, x - 1) + y * w,
            min(w - 1, x + 1) + y * w,
            x + max(    0, y - 1) * w,
            x + min(h - 1, y + 1) * w,
        };
    
        float a_sum = 0.0f;
    
        for (int d = 0; d < 4; d++){
            int j = js[d];
    
            float da = regularization + fabs(a0 - alpha[j]);
    
            a_sum += da;
    
            b00 += da * F_prev[j * 3 + 0];
            b01 += da * F_prev[j * 3 + 1];
            b02 += da * F_prev[j * 3 + 2];
    
            b10 += da * B_prev[j * 3 + 0];
            b11 += da * B_prev[j * 3 + 1];
            b12 += da * B_prev[j * 3 + 2];
        }
    
        float a00 = a0 * a0 + a_sum;
        float a11 = a1 * a1 + a_sum;
        float a01 = a0 * a1;
    
        float inv_det = 1.0f / (a00 * a11 - a01 * a01);
    
        F[i * 3 + 0] = fmax(0.0f, fmin(1.0f, inv_det * (a11 * b00 - a01 * b10)));
        F[i * 3 + 1] = fmax(0.0f, fmin(1.0f, inv_det * (a11 * b01 - a01 * b11)));
        F[i * 3 + 2] = fmax(0.0f, fmin(1.0f, inv_det * (a11 * b02 - a01 * b12)));
        B[i * 3 + 0] = fmax(0.0f, fmin(1.0f, inv_det * (a00 * b10 - a01 * b00)));
        B[i * 3 + 1] = fmax(0.0f, fmin(1.0f, inv_det * (a00 * b11 - a01 * b01)));
        B[i * 3 + 2] = fmax(0.0f, fmin(1.0f, inv_det * (a00 * b12 - a01 * b02)));
    }
    """
    
>   platform = cl.get_platforms()[0]
E   pyopencl._cl.LogicError: clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR

/usr/local/lib/python3.6/dist-packages/pymatting/foreground/estimate_foreground_ml_pyopencl.py:97: LogicError
===================================================================================================================== short test summary info ======================================================================================================================
FAILED tests/test_foreground.py::test_foreground - pyopencl._cl.LogicError: clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR
============================================================================================================= 1 failed, 10 passed in 61.21s (0:01:01) ==============================================================================================================
root@8108cd8da725:/pymatting# 



```

**Comment by tuelwer** [comment]
You might want to take a look at [this reddit-post](https://www.reddit.com/r/linux4noobs/comments/b0mu3e/trying_to_use_python_opencl_but_its_not_detecting/). Hope this is helpful!

**Comment by 99991** [comment]
This error message is likely caused by improperly installed OpenCL drivers.

Stackoverflow, the CUDA development forums and the PyOpenCL mailing list are probably good starting points to resolve this issue.

https://lists.tiker.net/hyperkitty/search?mlist=pyopencl%40tiker.net&q=PLATFORM_NOT_FOUND_KHR

**Comment by ghazni123** [comment]
Thank you. This is resolved.
