### ISSUE TITLE
when I run the examples on mac , report such error, any help?[Question❓]

### ISSUE THREAD

**Issue by miracletiger** [pymatting/pymatting#38]
/Users/mac/.conda/envs/yolov5/bin/python /Users/mac/PycharmProjects/aiphoto/pymatting/examples/advanced_example.py
Failed to import ahead-of-time-compiled modules.
This is expected on first import.
Compiling modules and trying again.
This might take a minute.
Traceback (most recent call last):
  File "/Users/mac/.conda/envs/yolov5/lib/python3.8/site-packages/pymatting_aot/cc.py", line 36, in <module>
    import pymatting_aot.aot
ModuleNotFoundError: No module named 'pymatting_aot.aot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mac/PycharmProjects/aiphoto/pymatting/examples/advanced_example.py", line 1, in <module>
    from pymatting import *
  File "/Users/mac/.conda/envs/yolov5/lib/python3.8/site-packages/pymatting/__init__.py", line 2, in <module>
    import pymatting_aot.cc
  File "/Users/mac/.conda/envs/yolov5/lib/python3.8/site-packages/pymatting_aot/cc.py", line 54, in <module>
    compile_modules()
  File "/Users/mac/.conda/envs/yolov5/lib/python3.8/site-packages/pymatting_aot/cc.py", line 18, in compile_modules
    cc.compile()
  File "/Users/mac/.conda/envs/yolov5/lib/python3.8/site-packages/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/mac/.conda/envs/yolov5/lib/python3.8/site-packages/numba/pycc/cc.py", line 217, in compile
    objects += self._compile_mixins(build_dir)
  File "/Users/mac/.conda/envs/yolov5/lib/python3.8/site-packages/numba/pycc/cc.py", line 187, in _compile_mixins
    objects = self._toolchain.compile_objects(sources, build_dir,
  File "/Users/mac/.conda/envs/yolov5/lib/python3.8/site-packages/numba/pycc/platform.py", line 137, in compile_objects
    objects = self._compiler.compile(sources,
  File "/Users/mac/.conda/envs/yolov5/lib/python3.8/site-packages/numpy/distutils/ccompiler.py", line 90, in <lambda>
    m = lambda self, *args, **kw: func(self, *args, **kw)
  File "/Users/mac/.conda/envs/yolov5/lib/python3.8/site-packages/numpy/distutils/ccompiler.py", line 356, in CCompiler_compile
    pool.map(single_compile, build_items)
  File "/Users/mac/.conda/envs/yolov5/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/mac/.conda/envs/yolov5/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/Users/mac/.conda/envs/yolov5/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/mac/.conda/envs/yolov5/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Users/mac/.conda/envs/yolov5/lib/python3.8/site-packages/numpy/distutils/ccompiler.py", line 321, in single_compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/Users/mac/.conda/envs/yolov5/lib/python3.8/site-packages/numpy/distutils/ccompiler.py", line 90, in <lambda>
    m = lambda self, *args, **kw: func(self, *args, **kw)
  File "/Users/mac/.conda/envs/yolov5/lib/python3.8/site-packages/numpy/distutils/unixccompiler.py", line 54, in UnixCCompiler__compile
    raise CompileError(msg)
distutils.errors.CompileError: Command "gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/mac/.conda/envs/yolov5/include -arch x86_64 -I/Users/mac/.conda/envs/yolov5/include -arch x86_64 -DPYCC_MODULE_NAME=aot -DPYCC_USE_NRT=1 -I/Users/mac/.conda/envs/yolov5/include/python3.8 -I/Users/mac/.conda/envs/yolov5/lib/python3.8/site-packages/numpy/core/include -c /Users/mac/.conda/envs/yolov5/lib/python3.8/site-packages/numba/pycc/modulemixin.c -o /var/folders/qg/j35fnxd56tn3mzf6sr_tw9q80000gn/T/pycc-build-aot-n738hml5/Users/mac/.conda/envs/yolov5/lib/python3.8/site-packages/numba/pycc/modulemixin.o" failed with exit status 1

**Comment by 99991** [comment]
Looks like the file `numba/pycc/modulemixin.c`, which is part of [numba](https://github.com/numba/numba), can not be compiled.

The first step is to make sure that `gcc` or something similar is installed.

Next, check if `numba` ahead-of-time compilation works by creating a file `test.py` with the following content and then run it.

```python3
import numpy as np
from numba.pycc import CC

cc = CC("my_module")

@cc.export('foo', 'f8[:](f8[:], f8[:])')
def foo(a, b):
    return a + b

cc.compile()

from my_module import foo

print(foo(
    np.float64([1, 2]),
    np.float64([3, 4])))
```

**Comment by 99991** [comment]
Closed due to inactivity. If you should find that the issue still exists, feel free to re-open.
